import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class LibraryTest {
    @Test
    void testSomeLibraryMethod() {
        Library classUnderTest = new Library();

        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
